### ISSUE TITLE
Tooltipの下の部分（:after）は本体側につける

### ISSUE THREAD

**Issue by 50ra4** [50ra4/ele-board-app#63]
```css
.tooltip:hover::after {
  content: "";
  position: absolute;
  bottom: calc(100% - 5px);
  left: 50%;
  margin-left: -5px;
  border-width: 5px;
  border-style: solid;
  border-color: #555 transparent transparent transparent;
}
```
